name: linker
description: Our app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # state management
  flutter_bloc: ^4.0.0
  shared_preferences: ^0.5.7
  # dart support
  equatable: ^1.1.1
  dartz: ^0.9.0
  data_connection_checker: ^0.3.4
  rxdart: ^0.24.0
  # service locator
  get_it: ^4.0.2
  # firebase
  firebase_auth: ^0.15.2
  cloud_firestore: ^0.13.5
  firebase_dynamic_links: ^0.5.0+11
  firebase_analytics: ^5.0.11
  # flare
  flare_flutter: ^2.0.3
  # UI
  cupertino_icons: ^0.1.3
  share: ^0.6.4
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  firebase_auth_mocks: ^0.1.3
  cloud_firestore_mocks: ^0.4.3+1
flutter:
  assets:
    - assets/images/app_icon.svg


  uses-material-design: true
