name: linker
description: Our app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # state management
  flutter_bloc: ^3.2.0
  shared_preferences: ^0.5.6+3
  # dart support
  equatable: ^1.1.1
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  # service locator
  get_it: ^4.0.1
  # firebase
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  # flare
  flare_flutter: ^2.0.2
  # UI
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
